name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLORCreate rust: always

jobs:


  build_and_test:
    runs-on: ubuntu/latest
    strategy:
        # On créé un matrice pour les deux architectures possibles. 
        matrix:
          platform: 
            - linux/amd64
            - linux/arm64
    steps:
    - uses: actions/checkout@v4

    # Si nous exécutons les tests sur ARM il faut installer QEMU pour émuler l'architecture. 
    - name: Mise en place de QEMU
      if: matrix.platform== 'linux/arm64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{matrix.platform}}
    - name: Run des tests sur l'archi ${{matrix.platform}}
      # On build l'image selon la plateforme considérée puis on la run.
      run: |
       docker build -t img --platform ${{matrix.platform}} . 
       docker run --rm --platform ${{matrix.platform}} img

